# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Board(object):
    def setupUi(self, Board):
        Board.setObjectName("Board")
        Board.resize(2931, 1853)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Board)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(60)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setLineWidth(3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.buttonBack = QtWidgets.QPushButton(Board)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.buttonBack.setFont(font)
        self.buttonBack.setObjectName("buttonBack")
        self.verticalLayout.addWidget(self.buttonBack)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.button00 = QtWidgets.QPushButton(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button00.sizePolicy().hasHeightForWidth())
        self.button00.setSizePolicy(sizePolicy)
        self.button00.setText("")
        self.button00.setObjectName("button00")
        self.gridLayout.addWidget(self.button00, 0, 0, 1, 1)
        self.button01 = QtWidgets.QPushButton(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button01.sizePolicy().hasHeightForWidth())
        self.button01.setSizePolicy(sizePolicy)
        self.button01.setText("")
        self.button01.setObjectName("button01")
        self.gridLayout.addWidget(self.button01, 0, 1, 1, 1)
        self.button02 = QtWidgets.QPushButton(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button02.sizePolicy().hasHeightForWidth())
        self.button02.setSizePolicy(sizePolicy)
        self.button02.setText("")
        self.button02.setObjectName("button02")
        self.gridLayout.addWidget(self.button02, 0, 2, 1, 1)
        self.button10 = QtWidgets.QPushButton(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button10.sizePolicy().hasHeightForWidth())
        self.button10.setSizePolicy(sizePolicy)
        self.button10.setText("")
        self.button10.setObjectName("button10")
        self.gridLayout.addWidget(self.button10, 1, 0, 1, 1)
        self.button11 = QtWidgets.QPushButton(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button11.sizePolicy().hasHeightForWidth())
        self.button11.setSizePolicy(sizePolicy)
        self.button11.setText("")
        self.button11.setObjectName("button11")
        self.gridLayout.addWidget(self.button11, 1, 1, 1, 1)
        self.button12 = QtWidgets.QPushButton(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button12.sizePolicy().hasHeightForWidth())
        self.button12.setSizePolicy(sizePolicy)
        self.button12.setText("")
        self.button12.setObjectName("button12")
        self.gridLayout.addWidget(self.button12, 1, 2, 1, 1)
        self.button20 = QtWidgets.QPushButton(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button20.sizePolicy().hasHeightForWidth())
        self.button20.setSizePolicy(sizePolicy)
        self.button20.setText("")
        self.button20.setObjectName("button20")
        self.gridLayout.addWidget(self.button20, 2, 0, 1, 1)
        self.button21 = QtWidgets.QPushButton(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button21.sizePolicy().hasHeightForWidth())
        self.button21.setSizePolicy(sizePolicy)
        self.button21.setText("")
        self.button21.setObjectName("button21")
        self.gridLayout.addWidget(self.button21, 2, 1, 1, 1)
        self.button22 = QtWidgets.QPushButton(Board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button22.sizePolicy().hasHeightForWidth())
        self.button22.setSizePolicy(sizePolicy)
        self.button22.setText("")
        self.button22.setObjectName("button22")
        self.gridLayout.addWidget(self.button22, 2, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Board)
        QtCore.QMetaObject.connectSlotsByName(Board)

    def retranslateUi(self, Board):
        _translate = QtCore.QCoreApplication.translate
        Board.setWindowTitle(_translate("Board", "Board"))
        self.label.setText(_translate("Board", "Tap the board to play"))
        self.label_2.setText(_translate("Board", "Things are happening in this zone, like the result of the match"))
        self.buttonBack.setText(_translate("Board", "Back"))

